# Generated by Django 5.0.6 on 2024-06-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_review'),
        ('users', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='owner',
            new_name='reviewer',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'project')},
        ),
    ]
